# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd26c90529a7cd2c842cbe12e338cec92e7cb0243a1f1a976a613207e3c345c1fc9d133853448be9502a8a53cd86d8e384900aced2ed0f4cd3cb4a68425d7fe4

test:
  secret_key_base: e90165ddb0aab38dfa41c114f659d92cb77e037a96f52cbd1150a248f4874c026d50f12032a6e9a47fa05c4bf8b4b5b38101cbd9847dc0c963ae3a5d1e7a4a42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
